### ISSUE TITLE
dpkg-buildpackage tries to write to /usr/share/doc/mpv, fails.

### ISSUE THREAD

**Issue by woolwood** [mpv-player/mpv-build#106]
I know using dpkg-buildpackage is not recommended, but as it’s still featured: `dpkg-buildpackage -uc -us -b -j8` fails at the end because it’s attempting to write to /usr/share/doc.

```
Waf: Entering directory `/home/adriaan/src/mpv-build/mpv/build'
[1/1] Compiling version.sh
Waf: Leaving directory `/home/adriaan/src/mpv-build/mpv/build'
Build failed
Traceback (most recent call last):
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Build.py", line 549, in run
    x.parent.mkdir()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 144, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
WafError: Could not create the directory /usr/share/doc/mpv

Traceback (most recent call last):
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Build.py", line 549, in run
    x.parent.mkdir()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 144, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
WafError: Could not create the directory /usr/share/doc/mpv

Traceback (most recent call last):
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Build.py", line 549, in run
    x.parent.mkdir()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 144, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
WafError: Could not create the directory /usr/share/doc/mpv

Traceback (most recent call last):
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Build.py", line 549, in run
    x.parent.mkdir()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 144, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
WafError: Could not create the directory /usr/share/doc/mpv

dh_installdirs: install -d debian/mpv returned exit code 1
debian/rules:30: recipe for target 'binary' failed
make: *** [binary] Error 2
```

Building on Debian 9.4

**Comment by kevmitch** [comment]
This just worked for me fine in a freshly upgraded 9.4 amd64 chroot. 

Does this still happen if from the `mpv-build` root you run

    ./build -j8
    scripts/mpv-clean
    scripts/mpv-config --prefix=/usr --confdir=/etc/mpv
    cd mpv && python waf -v install --destdir=../debian/mpv

Does your user own and or have permissions for the entire directory tree `/home/adriaan/src/mpv-build/debian/mpv/usr/share/`. It doesn't look like it by eye, but are any characters in that path non-ascii? I know that shouldn't make a difference, but I've seen waf choke on such things.

It's a little worrying that it's talking about the absolute path `/usr/share/doc/mpv` given it should be going to the path above inside the build directory. Though maybe this is just how waf handles the `--destdir=` option.

You haven't monkied with the waf version or anything have you?

**Comment by woolwood** [comment]
- My user owns everything in the mpv-build/ tree, there are no non-ascii characters in the path.
- The commands above do work, no errors reported.
- Also interesting: the above error happens on a clean clone with only `./update` and `dpkg-buildpackage -uc -us -b -j8`. Trying to run it again reports a different error, without building.

```
dpkg-buildpackage: info: source package mpv
dpkg-buildpackage: info: source version 2:2018.05.20.d828887792
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Local User <localuser@localhost>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build mpv-build
dpkg-source: info: using options from mpv-build/debian/source/options: --compression=xz --compression-level=best
 fakeroot debian/rules clean
exec dh clean
   dh_testdir
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/home/adriaan/src/mpv-build'
./clean
'distclean' finished successfully (0.009s)
make[1]: Leaving directory '/home/adriaan/src/mpv-build'
   dh_clean
 debian/rules build
exec dh build
   dh_testdir
   dh_update_autotools_config
The project was not configured: run "waf configure" first!
dh_update_autotools_config: install -d debian/.debhelper/bucket/files returned exit code 1
debian/rules:23: recipe for target 'build' failed
make: *** [build] Error 2
```

- I did not change any of the scripts.

**Comment by kevmitch** [comment]
what does it say if you first set

    $ export DH_VERBOSE=1

does the same thing happen if you create run it in a freshly created user account?

**Comment by woolwood** [comment]
Output with DH_VERBOSE=1, clean clone
```
[231/232] Linking build/mpv
[232/232] Compiling TOOLS/zsh.pl
Waf: Leaving directory `/home/adriaan/src/mpv-build/mpv/build'
'build' finished successfully (15.939s)
make[1]: Leaving directory '/home/adriaan/src/mpv-build'
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
 fakeroot debian/rules binary
exec dh binary
   create-stamp debian/debhelper-build-stamp
   dh_testroot
   dh_prep
	rm -f debian/mpv.substvars
	rm -f debian/mpv.*.debhelper
	rm -rf debian/mpv/
   debian/rules override_dh_auto_install
make[1]: Entering directory '/home/adriaan/src/mpv-build'
cd mpv && python waf -v install --destdir=../debian/mpv
Waf: Entering directory `/home/adriaan/src/mpv-build/mpv/build'
[1/1] Compiling version.sh
10:40:36 runner ' sh ../version.sh --cwd="/home/adriaan/src/mpv-build/mpv" --versionh="version.h" '
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/doc/mpv/mpv.conf (from etc/mpv.conf)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/doc/mpv/mplayer-input.conf (from etc/mplayer-input.conf)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/doc/mpv/input.conf (from etc/input.conf)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/doc/mpv/restore-old-bindings.conf (from etc/restore-old-bindings.conf)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/applications/mpv.desktop (from etc/mpv.desktop)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/man/man1/mpv.1 (from build/DOCS/man/mpv.1)
+ install /home/adriaan/src/mpv-build/debian/mpv/etc/mpv/encoding-profiles.conf (from etc/encoding-profiles.conf)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/icons/hicolor/64x64/apps/mpv.png (from etc/mpv-icon-8bit-64x64.png)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/icons/hicolor/scalable/apps/mpv.svg (from etc/mpv-gradient.svg)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/icons/hicolor/symbolic/apps/mpv-symbolic.svg (from etc/mpv-symbolic.svg)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/bin/mpv (from build/mpv)
+ install /home/adriaan/src/mpv-build/debian/mpv/usr/share/zsh/site-functions/_mpv (from build/etc/_mpv)
Waf: Leaving directory `/home/adriaan/src/mpv-build/mpv/build'
'install' finished successfully (0.900s)
make[1]: Leaving directory '/home/adriaan/src/mpv-build'
   dh_installdocs
	install -p -m0644 debian/copyright debian/mpv/usr/share/doc/mpv/copyright
Waf: Entering directory `/home/adriaan/src/mpv-build/mpv/build'
[1/1] Compiling version.sh
Waf: Leaving directory `/home/adriaan/src/mpv-build/mpv/build'
Build failed
Traceback (most recent call last):
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Build.py", line 549, in run
    x.parent.mkdir()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 144, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
WafError: Could not create the directory /usr/share/doc/mpv

Traceback (most recent call last):
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Build.py", line 549, in run
    x.parent.mkdir()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 144, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
WafError: Could not create the directory /usr/share/doc/mpv

Traceback (most recent call last):
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Build.py", line 549, in run
    x.parent.mkdir()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 144, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
WafError: Could not create the directory /usr/share/doc/mpv

Traceback (most recent call last):
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Build.py", line 549, in run
    x.parent.mkdir()
  File "/home/adriaan/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 144, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
WafError: Could not create the directory /usr/share/doc/mpv

dh_installdocs: install -p -m0644 debian/copyright debian/mpv/usr/share/doc/mpv/copyright returned exit code 1
debian/rules:30: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
dpkg-buildpackage -uc -us -b -j8  1176.84s user 54.22s system 548% cpu 3:44.49 total
```

Output running again: 
```
dpkg-buildpackage: info: source package mpv
dpkg-buildpackage: info: source version 2:2018.05.20.d828887792
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Local User <localuser@localhost>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build mpv-build
dpkg-source: info: using options from mpv-build/debian/source/options: --compression=xz --compression-level=best
 fakeroot debian/rules clean
exec dh clean
   dh_testdir
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/home/adriaan/src/mpv-build'
./clean
make[2]: Entering directory '/home/adriaan/src/mpv-build/libass'
Making distclean in libass
make[3]: Entering directory '/home/adriaan/src/mpv-build/libass/libass'
test -z "libass.la" || rm -f libass.la
rm -f ./so_locations
rm -rf .libs _libs
rm -rf x86/.libs x86/_libs
rm -f *.o
rm -f x86/*.o
rm -f x86/*.lo
rm -f *.lo
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f x86/.deps/.dirstamp
rm -f x86/.dirstamp
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -rf ./.deps
rm -f Makefile
make[3]: Leaving directory '/home/adriaan/src/mpv-build/libass/libass'
Making distclean in test
make[3]: Entering directory '/home/adriaan/src/mpv-build/libass/test'
rm -rf .libs _libs
 rm -f test
rm -f *.o
rm -f *.lo
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -rf ./.deps
rm -f Makefile
make[3]: Leaving directory '/home/adriaan/src/mpv-build/libass/test'
Making distclean in profile
make[3]: Entering directory '/home/adriaan/src/mpv-build/libass/profile'
rm -rf .libs _libs
 rm -f profile
rm -f *.o
rm -f *.lo
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -rf ./.deps
rm -f Makefile
make[3]: Leaving directory '/home/adriaan/src/mpv-build/libass/profile'
make[3]: Entering directory '/home/adriaan/src/mpv-build/libass'
rm -rf .libs _libs
rm -f *.lo
test -z "libass.pc" || rm -f libass.pc
test . = "." || test -z "" || rm -f 
rm -f config.h stamp-h1
rm -f libtool config.lt
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
make[3]: Leaving directory '/home/adriaan/src/mpv-build/libass'
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -f Makefile
make[2]: Leaving directory '/home/adriaan/src/mpv-build/libass'
'distclean' finished successfully (0.037s)
make[1]: Leaving directory '/home/adriaan/src/mpv-build'
   dh_clean
	rm -f debian/debhelper-build-stamp
	rm -f debian/mpv.substvars
	rm -f debian/mpv.*.debhelper
	rm -rf debian/mpv/
	rm -rf debian/.debhelper/
	rm -f debian/*.debhelper.log
	rm -f debian/files
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
	rm -f *-stamp
 debian/rules build
exec dh build
   dh_testdir
   dh_update_autotools_config
	install -d debian/.debhelper/bucket/files
The project was not configured: run "waf configure" first!
dh_update_autotools_config: install -d debian/.debhelper/bucket/files returned exit code 1
debian/rules:23: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

Ah. The .deb package does indeed get built without issue using a freshly created user account.

**Comment by kevmitch** [comment]
> Ah. The .deb package does indeed get built without issue using a freshly created user account.

In the first case, it looks like it's incorrectly executing waf install a second time for unknown reasons. Ordinarily this shouldn't be a problem, but for some reason it is. 

In the second, it's running waf ` override_dh_auto_build` before `override_dh_auto_configure` is completed. This obviously shouldn't happen

If it works in a fresh account, you might have some DEB_.. (or other) environment variables set.

**Comment by kevmitch** [comment]
ok, well there're obviously tools in there that the dpkg-buildpackage process is finding and using over system ones. obviously dpkg-buildpackage can't support that. a little curious as to what those overridden tools are and why they could cause such weird issues though.

**Comment by woolwood** [comment]
Actually no, that’s not what’s happening. The problem was setting PATH=**:**. Removing the apparently misplaced colon solves the issue. Which I still find weird…
