### ISSUE TITLE
" OpenGL video output found or enabled" on Intel NUC 

### ISSUE THREAD

**Issue by AlexKratky** [mpv-player/mpv-build#174]
Hello, I am trying to build mpv on my own, but I keep getting this error: "OpenGL video output found or enabled"

Last lines of config.log

```
Checking for Direct3D 11 video output
win32-desktop not found
-------------------------------------------------------------------------
Checking for iOS OpenGL ES hardware decoding interop support
==>
#include <OpenGLES/ES3/glext.h>
int main(int argc, char **argv)
{ (void)GL_RGB32F; return 0; }
<==
[1/2] Compiling [32mbuild/.conf_check_215e0decd6b96b61d7e6017ad5da5b7c/test.c[0m

['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_FILE_OFFSET_BITS=64', '-Wall', '-std=c11', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wno-format-truncation', '-Wimplicit-fallthrough', '-fno-math-errno', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-DDEFAULT_DVD_DEVICE="/dev/sr0"', '-DDEFAULT_CDROM_DEVICE="/dev/sr0"', '-DHAVE_GPL=1', '-DHAVE_CPLAYER=1', '-DHAVE_BUILD_DATE=1', '-DHAVE_OPTIMIZE=1', '-DHAVE_DEBUG_BUILD=1', '-DHAVE_LIBDL=1', '-DHAVE_CPLUGINS=1', '-DHAVE_ASM=1', '-DHAVE_VECTOR=1', '-DHAVE_LIBM=1', '-DHAVE_POSIX=1', '-DHAVE_POSIX_OR_MINGW=1', '-DHAVE_PTHREADS=1', '-DHAVE_STDATOMIC=1', '-DHAVE_LIBRT=1', '-DHAVE_ICONV=1', '-DHAVE_GLOB_POSIX=1', '-DHAVE_GLOB=1', '-DHAVE_VT_H=1', '-DHAVE_GLIBC_THREAD_NAME=1', '-DHAVE_LINUX_FSTATFS=1', '-DHAVE_LINUX_INPUT_EVENT_CODES=1', '-DHAVE_LIBASS=1', '-DHAVE_ZLIB=1', '-DHAVE_FFMPEG=1', '-DHAVE_LIBAVDEVICE=1', '-DHAVE_FFMPEG_AVIOCONTEXT_BYTES_READ=1', '-DHAVE_PULSE=1', '-DHAVE_ALSA=1', '-DHAVE_DRM=1', '-DHAVE_EGL=1', '-DHAVE_CACA=1', '../test.c', '-c', '-o/home/alex/mpv/mpv-build/mpv/build/.conf_check_215e0decd6b96b61d7e6017ad5da5b7c/testbuild/test.c.1.o']
err: ../test.c:1:10: fatal error: OpenGLES/ES3/glext.h: No such file or directory
    1 | #include <OpenGLES/ES3/glext.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

from /home/alex/mpv/mpv-build/mpv: Test does not build: Traceback (most recent call last):
  File "/home/alex/mpv/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Configure.py", line 335, in run_build
    bld.compile()
  File "/home/alex/mpv/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Build.py", line 176, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 1 (run with -v to display more information)

from /home/alex/mpv/mpv-build/mpv: The configuration failed
no
-------------------------------------------------------------------------
Checking for OpenGL without platform-specific code (e.g. for libmpv)
libmpv-shared not found
-------------------------------------------------------------------------
Checking for OpenGL context support
gl-cocoa not found
```

I am not sure which libraries I am missing?

**Comment by CounterPillow** [comment]
What distribution? If it's one that splits development headers from regular packages, then you're probably missing a lot of -dev (or -devel depending on distro) packages. On Debian and derivatives, you can install them with `sudo apt build-deps mpv`.

**Comment by AlexKratky** [comment]
@CounterPillow I am using Linux Mate 20, there is prebuild v0.32, but I need v0.34. I will try to install that packages

**Comment by Dudemanguy** [comment]
waf support no longer exists and if my memory is right the logic here is a bit different in meson. Anyways, feel free to open a new issue if this problem still exists.
