### ISSUE TITLE
./rebuild fails on RPi3, No OpenGL video output found or enabled.

### ISSUE THREAD

**Issue by LaggAt** [mpv-player/mpv-build#92]
Hi, 

after retrying and researching for days now i finally need help on compiling. I read and tried the solutions here in open issues, researched web, and finally found that information here:

https://nwgat.ninja/quick-easy-compiling-mpv-for-raspberry-pi/

Conclusion: using the process described there I get further, but I am still stuck. So, here are my details:

I tried this:

```
git clone https://github.com/mpv-player/mpv-build.git
cd ~/src/mpv-build
echo --enable-mmal >> ffmpeg_options
export PKG_CONFIG_PATH=/opt/vc/lib/pkgconfig/
export LIBRARY_PATH=/opt/vc/lib
./use-mpv-master
./use-ffmpeg-master
./update
./rebuild -j4 ; pushbullet.sh "Done. Exited $?"
```
Logs:

./libass/config.log: http://paste.ubuntu.com/25679121/
./mpv/build/config.log: http://paste.ubuntu.com/25679122/
./ffmpeg_build/ffbuild/config.log: http://paste.ubuntu.com/25679123/
sudo dpkg -l: http://paste.ubuntu.com/25679152/

I'm out of ideas. I also tried combinations of these flags, but removed them for now to get it running:

#echo --enable-gpl >> ffmpeg_options
#echo --enable-omx >> ffmpeg_options
#echo --enable-omx-rpi >> ffmpeg_options
#echo --enable-nonfree >> ffmpeg_options
#echo --disable-rpi >> mpv_options
#echo --enable-rpi >> mpv_options

What can I do?

**Comment by wm4** [comment]
```
['/usr/bin/cc', 'test.c.1.o', '-o/home/pi/src/mpv-build/mpv/build/.conf_check_4007429513c0b542ef3d833f4ba30280/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-lEGL']
err: /opt/vc/lib/libEGL.so: undefined reference to `glxx_buffer_info_set'
/opt/vc/lib/libEGL.so: undefined reference to `glBufferSubData'
/opt/vc/lib/libEGL.so: undefined reference to `glxx_client_GetFramebufferAttachmentParameteriv'
/opt/vc/lib/libEGL.so: undefined reference to `glxx_client_state_free'
```

Something seems wrong with the RPI libEGL. We can't really help with that. The RPI userland is hopelessly broken and inconsistent.

**Comment by wm4** [comment]
Actually scratch that - this was the check for MALI, which should obviously fail on RPI.

I don't see the RPI check being run in your mpv log.

**Comment by LaggAt** [comment]
Ok, scratched. Thanks for your really quick response. Anything else I could do?

**Comment by wm4** [comment]
Find where/how the mpv configure RPI check is run and quote the log output.

**Comment by wm4** [comment]
PS: I'm also not sure what fails for you to be honest. There is no error message or explanation anywhere.

**Comment by LaggAt** [comment]
Hi, I'm sorry, probably missed that. I get:

No OpenGL video output found or enabled.
when running ./rebuild -j4

This looks promising - how can I find that test in source? 
```
Checking for dynamic loader
==>
#include <dlfcn.h>
int main(int argc, char **argv)
{ dlopen("", 0); return 0; }
<==
[1/2] Compiling [32mbuild/.conf_check_cdc8c167cee8ec25db9fd2fd3ebce9a1/test.c[0m

['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-DDEFAULT_DVD_DEVICE="/dev/sr0"', '-DDEFAULT_CDROM_DEVICE="/dev/sr0"', '-DHAVE_GPL=1', '-DHAVE_LIBAF=1', '-DHAVE_CPLAYER=1', '-DHAVE_BUILD_DATE=1', '-DHAVE_OPTIMIZE=1', '-DHAVE_DEBUG_BUILD=1', '../test.c', '-c', '-o/home/pi/src/mpv-build/mpv/build/.conf_check_cdc8c167cee8ec25db9fd2fd3ebce9a1/testbuild/test.c.1.o']
[2/2] Linking [33mbuild/.conf_check_cdc8c167cee8ec25db9fd2fd3ebce9a1/testbuild/testprog[0m

['/usr/bin/cc', 'test.c.1.o', '-o/home/pi/src/mpv-build/mpv/build/.conf_check_cdc8c167cee8ec25db9fd2fd3ebce9a1/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic']
err: test.c.1.o: In function `main':
/home/pi/src/mpv-build/mpv/build/.conf_check_cdc8c167cee8ec25db9fd2fd3ebce9a1/testbuild/../test.c:3: undefined reference to `dlopen'
collect2: error: ld returned 1 exit status

from /home/pi/src/mpv-build/mpv: Test does not build: Traceback (most recent call last):
  File "/home/pi/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Configure.py", line 324, in run_build
    bld.compile()
  File "/home/pi/src/mpv-build/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Build.py", line 181, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed with exit status 1 (run with -v to display more information)

from /home/pi/src/mpv-build/mpv: The configuration failed
==>
```

**Comment by wm4** [comment]
Can you just post the console log. This doesn't help.

**Comment by LaggAt** [comment]
Ok, didn't capture this, so this takes some while. I'll return to you asap. Thanks.

**Comment by wm4** [comment]
You can just not recompile ffmpeg by running `scripts/mpv-config` and `scripts/mpv-build` directly.

**Comment by LaggAt** [comment]
mpv-config fails. Thanks for that info, this saves a lot of time :)

http://paste.ubuntu.com/25679386/
The pastebin is ugly, because of the colors. I'll post the probably relevant part here:

```
Checking for wayland-scanner                                      : yes
Checking for wayland-protocols                                    : yes
Checking for Wayland                                              : no ('wayland-client >= 1.6.0 wayland-cursor >= 1.6.0 xkbcommon >= 0.3.0' not found)
Checking for X11                                                  : no ('x11 >= 1.0.0 xscrnsaver >= 1.0.0 xext >= 1.0.0 xinerama >= 1.0.0 xrandr >= 1.2.0' not found)
Checking for Xv video output                                      : x11 not found
Checking for OpenGL Cocoa Backend                                 : cocoa not found
Checking for OpenGL X11 Backend                                   : x11 not found
Checking for OpenGL X11 EGL Backend                               : x11 not found
Checking for OpenGL DRM EGL Backend                               : gbm not found
Checking for OpenGL Wayland Backend                               : wayland not found
Checking for OpenGL Win32 Backend                                 : win32-desktop not found
Checking for OpenGL/DirectX Interop Backend                       : gl-win32 not found
Checking for OpenGL ANGLE headers                                 : os-win32 not found
Checking for OpenGL Win32 ANGLE Library                           : egl-angle not found
Checking for OpenGL Win32 ANGLE Backend                           : egl-angle not found
Checking for VDPAU acceleration                                   : x11 not found
Checking for VDPAU with OpenGL/X11                                : vdpau not found
Checking for VAAPI acceleration                                   : x11 not found
Checking for VAAPI (X11 support)                                  : vaapi not found
Checking for VAAPI (Wayland support)                              : vaapi not found
Checking for VAAPI (DRM/EGL support)                              : vaapi not found
Checking for VAAPI GLX                                            : vaapi-x11 not found
Checking for VAAPI EGL on X11                                     : vaapi-x11 not found
Checking for VAAPI EGL                                            : vaapi-x-egl not found
Checking for CACA                                                 : yes
Checking for JPEG support                                         : yes
Checking for Direct3D support                                     : win32-desktop not found
Checking for Raspberry Pi support                                 : no
Checking for iOS OpenGL ES hardware decoding interop support      : no
Checking for OpenGL without platform-specific code (e.g. for libmpv) : libmpv-shared not found
Checking for MALI via Linux fbdev                                    : no
Checking for OpenGL context support                                  : gl-cocoa not found
```

I understand it doesn't find any opengl implementation. I dont really know what it should find on an RPi3. I'm also unsure if "Raspberry Pi support" is ment for all RPi's or only the 2nd version, I already googled about that. 

Is this what you wanted?

**Comment by LaggAt** [comment]
Oh, another information - in 'sudo raspi-config' this option is enabled:
"G1 GL (Full KMS) OpenGL desktop driver with full KMS"

**Comment by wm4** [comment]
That's still not all output...

**Comment by LaggAt** [comment]
This is the output of:
./scripts/mpv-config 2>&1 >/tmp/mpv-config.log

I didn't cut the pastebin, so what I am supposed to do?

**Comment by wm4** [comment]
It should print either an error or success at the end. Are you really not seeing something like that on the terminal?

**Comment by LaggAt** [comment]
Ok, forwarding to file cut the stderr. Sorry for that. 

`No OpenGL video output found or enabled. Aborting. If you really mean to compile without OpenGL video outputs use --disable-gl.`

**Comment by LaggAt** [comment]
Well, I don't really mean that (compile without OpenGL)

**Comment by wm4** [comment]
This definitely happens because of ```Checking for Raspberry Pi support                                 : no```, but the check doesn't appear in your mpv waf build log.

**Comment by LaggAt** [comment]
Ok, give me some minutes to check if there is something swallowed in the log by using 2>&1.
Meanwhile, Thanks.

**Comment by wm4** [comment]
I meant Raspberry PI. I overlooked this the first time, and it's actually in the log:
```
Checking for Raspberry Pi support
==>
#include <bcm_host.h>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling [32mbuild/.conf_check_c858465d4c24b433957f8cf0edcf6383/test.c[0m

['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-isystem/opt/vc/include/', '-isystem/opt/vc/include/interface/vcos/pthreads', '-isystem/opt/vc/include/interface/vmcs_host/linux', '-fgnu89-inline', '-DDEFAULT_DVD_DEVICE="/dev/sr0"', '-DDEFAULT_CDROM_DEVICE="/dev/sr0"', '-DHAVE_GPL=1', '-DHAVE_LIBAF=1', '-DHAVE_CPLAYER=1', '-DHAVE_BUILD_DATE=1', '-DHAVE_OPTIMIZE=1', '-DHAVE_DEBUG_BUILD=1', '-DHAVE_LIBDL=1', '-DHAVE_CPLUGINS=1', '-DHAVE_ASM=1', '-DHAVE_LIBM=1', '-DHAVE_POSIX=1', '-DHAVE_POSIX_OR_MINGW=1', '-DHAVE_PTHREADS=1', '-DHAVE_GNUC=1', '-DHAVE_STDATOMIC=1', '-DHAVE_ATOMICS=1', '-DHAVE_LIBRT=1', '-DHAVE_ICONV=1', '-DHAVE_TERMIOS_H=1', '-DHAVE_TERMIOS=1', '-DHAVE_SHM=1', '-DHAVE_NANOSLEEP=1', '-DHAVE_POSIX_SPAWN_NATIVE=1', '-DHAVE_POSIX_SPAWN=1', '-DHAVE_GLOB_POSIX=1', '-DHAVE_GLOB=1', '-DHAVE_FCHMOD=1', '-DHAVE_VT_H=1', '-DHAVE_GLIBC_THREAD_NAME=1', '-DHAVE_LINUX_FSTATFS=1', '-DHAVE_51OBSD=1', '-DHAVE_LUA=1', '-DHAVE_LIBASS=1', '-DHAVE_LIBASS_OSD=1', '-DHAVE_ZLIB=1', '-DHAVE_ENCODING=1', '-DHAVE_LIBBLURAY=1', '-DHAVE_OSS_AUDIO=1', '-DHAVE_PULSE=1', '-DHAVE_JACK=1', '-DHAVE_ALSA=1', '-DHAVE_DRM=1', '-DHAVE_WAYLAND_PROTOCOLS=1', '-DHAVE_CACA=1', '-DHAVE_JPEG=1', '../test.c', '-c', '-o/home/pi/src/mpv-build/mpv/build/.conf_check_c858465d4c24b433957f8cf0edcf6383/testbuild/test.c.1.o']
[2/2] Linking [33mbuild/.conf_check_c858465d4c24b433957f8cf0edcf6383/testbuild/testprog[0m

['/usr/bin/cc', '-L/opt/vc/lib', 'test.c.1.o', '-o/home/pi/src/mpv-build/mpv/build/.conf_check_c858465d4c24b433957f8cf0edcf6383/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-lmmal_core', '-lmmal_util', '-lmmal_vc_client', '-lbcm_host']
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling [32mbuild/.conf_check_27fef0a8d2630fbcf770b20b0b03c4f0/test.c[0m

['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-DDEFAULT_DVD_DEVICE="/dev/sr0"', '-DDEFAULT_CDROM_DEVICE="/dev/sr0"', '-DHAVE_GPL=1', '-DHAVE_LIBAF=1', '-DHAVE_CPLAYER=1', '-DHAVE_BUILD_DATE=1', '-DHAVE_OPTIMIZE=1', '-DHAVE_DEBUG_BUILD=1', '-DHAVE_LIBDL=1', '-DHAVE_CPLUGINS=1', '-DHAVE_ASM=1', '-DHAVE_LIBM=1', '-DHAVE_POSIX=1', '-DHAVE_POSIX_OR_MINGW=1', '-DHAVE_PTHREADS=1', '-DHAVE_GNUC=1', '-DHAVE_STDATOMIC=1', '-DHAVE_ATOMICS=1', '-DHAVE_LIBRT=1', '-DHAVE_ICONV=1', '-DHAVE_TERMIOS_H=1', '-DHAVE_TERMIOS=1', '-DHAVE_SHM=1', '-DHAVE_NANOSLEEP=1', '-DHAVE_POSIX_SPAWN_NATIVE=1', '-DHAVE_POSIX_SPAWN=1', '-DHAVE_GLOB_POSIX=1', '-DHAVE_GLOB=1', '-DHAVE_FCHMOD=1', '-DHAVE_VT_H=1', '-DHAVE_GLIBC_THREAD_NAME=1', '-DHAVE_LINUX_FSTATFS=1', '-DHAVE_51OBSD=1', '-DHAVE_LUA=1', '-DHAVE_LIBASS=1', '-DHAVE_LIBASS_OSD=1', '-DHAVE_ZLIB=1', '-DHAVE_ENCODING=1', '-DHAVE_LIBBLURAY=1', '-DHAVE_OSS_AUDIO=1', '-DHAVE_PULSE=1', '-DHAVE_JACK=1', '-DHAVE_ALSA=1', '-DHAVE_DRM=1', '-DHAVE_WAYLAND_PROTOCOLS=1', '-DHAVE_CACA=1', '-DHAVE_JPEG=1', '../test.c', '-c', '-o/home/pi/src/mpv-build/mpv/build/.conf_check_27fef0a8d2630fbcf770b20b0b03c4f0/testbuild/test.c.1.o']
[2/2] Linking [33mbuild/.conf_check_27fef0a8d2630fbcf770b20b0b03c4f0/testbuild/testprog[0m

['/usr/bin/cc', 'test.c.1.o', '-o/home/pi/src/mpv-build/mpv/build/.conf_check_27fef0a8d2630fbcf770b20b0b03c4f0/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-lEGL']
err: /opt/vc/lib/libEGL.so: undefined reference to `glxx_buffer_info_set'
/opt/vc/lib/libEGL.so: undefined reference to `glBufferSubData'
/opt/vc/lib/libEGL.so: undefined reference to `glxx_client_GetFramebufferAttachmentParameteriv'
/opt/vc/lib/libEGL.so: undefined reference to `glxx_client_state_free'
```
Fails similarly to the Mali test, because libEGL simply doesn't link. Sorry for the chase.

You could check if this PR builds:
https://github.com/mpv-player/mpv/pull/4883

**Comment by LaggAt** [comment]
You don't have to be sorry, your support is great. 
I did start the ./rebuild to see if there was something missing - so I have to wait for it to finish.

I'll try & come back.

**Comment by LaggAt** [comment]
./scripts/mpv-config: 'configure' finished successfully (17.886s)

But now mpv-build complains ... 

```
[182/221] Compiling video/out/opengl/context_rpi.c
../video/out/opengl/context_rpi.c:21:22: fatal error: bcm_host.h: Datei oder Verzeichnis nicht gefunden
 #include <bcm_host.h>
                      ^
compilation terminated.

Waf: Leaving directory `/home/pi/src/mpv-build/mpv/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
```

The file exists:
```
pi@BRAIN:~/src/mpv-build $ find /opt/vc/ -name bcm_host.h
/opt/vc/include/bcm_host.h
```
but somehow isn't found. I need to stop for today, I'll investigate tomorrow. Big thanks!

**Comment by LaggAt** [comment]
So, 
`export CPATH=/opt/vc/include/
./scripts/mpv-config 
./scripts/mpv-build 
sudo ./install`

That worked now. Great thanks.
